version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    binary: mmd
    main: ./cmd/mmd/

archives:
  - formats: [tar.gz]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      mmd_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

# Publish on Homebrew Tap
brews:
- name: mmd 
  repository:
    owner: mrueg
    name: homebrew-tap
    branch: main
    token: "{{ .Env.TAP_GITHUB_TOKEN }}"

  commit_author:
    name: Manuel Rüger
    email: manuel@rueg.eu

  commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"

  directory: Formula

  homepage: "https://github.com/mrueg/go-mermaid"
  description: "CLI tool to create mermaid diagrams"
  license: "MIT"

  install: |
    bin.install "mmd"
    generate_completions_from_executable(bin/"mmd", "completion")

  test: |
    system "#{bin}/mmd", "version"
